export const STORAGE_KEYS = {
  CATEGORIES: 'trax_categories',
};

export const OPERATION_KEYS = {
  CACHED_USER: 'trax_user',
  USE_BIOMETRIC: 'trax_use_biometric',
  LAST_SYNC: 'trax_last_sync',
  SELECTED_WALLET: 'trax_selected_wallet',
  FREQUENT_CATEGORIES: 'trax_frequent-categories',
};

export const DATABASE_NAME = 'trax_database';

export const CATEGORY_COLORS = [
  'red',
  'orange',
  'amber',
  'yellow',
  'lime',
  'green',
  'emerald',
  'teal',
  'cyan',
  'sky',
  'blue',
  'indigo',
  'violet',
  'purple',
  'fuchsia',
  'pink',
  'rose',
  'slate',
  'gray',
  'neutral',
];

export const CATEGORY_ICONS = [
  // Nhóm 1: Food, Drinks & Shopping (Dữ liệu của bạn)
  'restaurant',
  'wine',
  'nutrition',
  'fast-food',
  'bag-handle',
  'shirt',
  'medical',
  'laptop',
  'happy',
  'gift',
  'beaker',
  'home',
  'diamond',
  'cart',
  'paw',
  'construct',

  // Nhóm 2: Housing & Transport (Dữ liệu của bạn)
  'bulb',
  'hammer',
  'cash',
  'business',
  'key',
  'settings',
  'bus',
  'briefcase',
  'airplane',
  'train',
  'car',
  'car-sport',
  'speedometer',
  'square',
  'person',
  'barbell',

  // Nhóm 3: Life & Communication (Dữ liệu của bạn)
  'library',
  'ticket',
  'school',
  'heart',
  'umbrella',
  'calendar',
  'dice',
  'tv',
  'flower',
  'wifi',
  'call',
  'mail',
  'download',
  'people',
  'swap-vertical',
  'document-text',

  // Nhóm 4: Financial & Investment (Dữ liệu của bạn)
  'shield-checkmark',
  'wallet',
  'receipt',
  'stats-chart',
  'apps',
  'trending-up',
  'save',
  'create',
  'checkmark-circle',
  'podium',
  'arrow-down-circle',
  'refresh',

  // Nhóm 5: Bổ sung để tròn mảng & Đa dạng (Chia hết cho 4)
  'share',
  'menu',
  'notifications',
  'camera',
  'game-controller',
  'leaf',
  'trophy',
  'water',
  'flashlight',
  'alarm',
  'medkit',
  'calculator',
];
